chore: fix some comments
krzyzanowskim/CryptoSwift pull request #1050
Opened 2024-06-13 04:00 UTC by dropbigfish

fix some comments

Checklist:
- [ ] Correct file headers (see CONTRIBUTING.md).
- [ ] Formatted with [SwiftFormat](https://github.com/nicklockwood/SwiftFormat).
- [ ] Tests added.

Changes proposed in this pull request:
-

2024-06-14 12:10 UTC, nathanfallet requested changes

2024-06-14 12:10 UTC, nathanfallet commented on Sources/CryptoSwift/StreamEncryptor.swift
> +    // omit necessary calculation if not needed
This change changes the meaning

2024-06-14 12:10 UTC, nathanfallet commented on Sources/CryptoSwift/StreamDecryptor.swift
> +    // omit necessary calculation if not needed
Same

2024-10-15 15:47 UTC, krzyzanowskim approved these changes
LGTM. thank you

2024-10-15 15:47 UTC, merged